services:
  sender:
    build: ./sender
    environment:
      - DEST_IP=receiver
      - DEST_PORT=5000

  receiver:
    build: ./receiver
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs  # ✅ Mounts local 'logs' folder
