name: Run Latency Test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Compose
        run: docker-compose --version
      - name: Build and run containers
        run: |
          docker compose up --build -d
          # Let the containers run for 30 seconds to gather data
          sleep 30
          docker compose logs
          docker compose down
