name: Run Latency Test with Visualization

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker Compose version
        run: docker compose version

      - name: Build and run containers
        run: |
          docker compose up --build -d
          sleep 60  # Let receiver collect latency data
          docker compose logs
          docker compose down

      - name: Set up Python environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install pandas matplotlib

      - name: Generate latency plot
        run: python3 plot_latency.py

      - name: Upload CSV log
        uses: actions/upload-artifact@v4
        with:
          name: latency-log
          path: logs/latency_log.csv

      - name: Upload latency plot
        uses: actions/upload-artifact@v4
        with:
          name: latency-graph
          path: logs/latency_plot.png
